### ISSUE TITLE
When trying to start

### ISSUE THREAD

**Issue by ivanjeremic** [yogaboll/react-kanban#10]
[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node dist/server.js dist/server.js`
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'C:\Users\ivnj\Development\NodeProjects\kanban\react-kanban\dist\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by daeschwed** [comment]
@texxxo You need to build the project before starting it
```shell
npm run build
```

Depending on your needs, you may want to check out the simplified setup to skip setting up all dependencies
```shell
git checkout simple-dev
```

Refer to the README.md for detailed instructions how to get up and running.

Hope that helps, otherwise leave a comment and we'll sort it out.

Cheers and a happy new year to y'all.
